version: "3"
services:
        aha:
            container_name: aha
            image: ampirzadeh/aha
            restart: always
            build: .
            environment:
              - PORT=8080
              - DEBUG=aha:*
              - MONGODB_CONNSTRING=mongodb://ampirzadeh:cdV4R5GO35vj@localhost:27018/aha 
            ports:
              - 8080:8080
            links:
              - mongo
        mongo:
              container_name: mongo
              image: mongo:5.0
              volumes:
                - ./data:/data/db
              ports:
                - 27018:27017